# Build the EPV-model input table for the real-match test fixture.
# Mirrors the chain in data-raw/epv/01_train_epv_models.R (EPV_METHOD = "xg"):
#   spadl -> chains -> outcomes -> labeled actions -> next-goal/next-xG labels
#   -> create_epv_features_simple() == the `features` arg of fit_epv_model().
# Run from panna/:  Rscript data-raw/make_epv_fixture.R
# Requires tests/testthat/fixtures/opta_match_events_epl.parquet
#   (generated by data-raw/make_spadl_fixture.R)

devtools::load_all(".", quiet = TRUE)

fix_dir <- file.path("tests", "testthat", "fixtures")
events_path <- file.path(fix_dir, "opta_match_events_epl.parquet")
stopifnot(file.exists(events_path))
events <- arrow::read_parquet(events_path)
cat("Raw events fixture:", nrow(events), "rows (match",
    unique(events$match_id), ")\n")

spadl <- convert_opta_to_spadl(events)
spadl$league <- "EPL"

chains <- create_possession_chains(spadl)
outcomes <- classify_chain_outcomes(chains)
outcomes <- add_next_chain_outcome(outcomes)
labeled <- label_actions_with_outcomes(chains, outcomes)
labeled <- create_next_goal_labels(labeled)
labeled <- create_next_xg_labels(labeled)  # production EPV_METHOD = "xg"

labeled <- data.table::as.data.table(labeled)
data.table::setorder(labeled, match_id, period_id, time_seconds, action_id)

epv_input <- data.table::as.data.table(create_epv_features_simple(labeled))
stopifnot(nrow(epv_input) == nrow(labeled))

arrow::write_parquet(labeled, file.path(fix_dir, "spadl_labeled_epl.parquet"))
arrow::write_parquet(epv_input, file.path(fix_dir, "epv_input_epl.parquet"))

cat("\nspadl_labeled :", nrow(labeled), "rows x", ncol(labeled), "cols\n")
cat("epv_input     :", nrow(epv_input), "rows x", ncol(epv_input), "cols\n")
cat("epv_input columns:\n ", paste(names(epv_input), collapse = ", "), "\n")
cat("label columns:\n ",
    paste(grep("next_|chain_", names(labeled), value = TRUE), collapse = ", "),
    "\n")
for (f in c("spadl_labeled_epl.parquet", "epv_input_epl.parquet")) {
  p <- file.path(fix_dir, f)
  cat(sprintf("%-30s %.0f KB\n", f, file.size(p) / 1024))
}
