# 04_export_xmetrics.R
# Consolidate per-league/season xmetrics into a single parquet and upload
# to GitHub Releases (opta-latest tag) as opta_xmetrics.parquet.
#
# Run from panna directory: Rscript data-raw/epv/04_export_xmetrics.R
#
# Requires:
#   - pannadata/data/opta/xmetrics/{league}/{season}.parquet files
#     (generated by 03_calculate_player_xmetrics.R)
#
# Outputs:
#   - Uploads opta_xmetrics.parquet to peteowen1/pannadata opta-latest release

library(cli)
library(arrow)
devtools::load_all()
source("data-raw/epv/_xmetrics_export_common.R")

cli_h1("Export xMetrics to GitHub Releases")

# Config override pattern: set XMETRICS_UPLOAD <- FALSE before sourcing to
# consolidate locally without publishing. See 04b for the rationale.
# Plain exists(), NOT inherits = FALSE - see 04b for why.
if (!exists("XMETRICS_UPLOAD")) XMETRICS_UPLOAD <- TRUE

cli_h2("Step 1: Consolidate xmetrics")
combined <- export_consolidated_xmetrics("xmetrics", "opta_xmetrics.parquet", "player-seasons",
                                         upload = XMETRICS_UPLOAD)

cli_h2("Summary")

leagues <- if ("league" %in% names(combined)) unique(combined$league) else "unknown"
seasons <- if ("season" %in% names(combined)) range(combined$season) else "unknown"

cli_alert_success(paste0(
  if (XMETRICS_UPLOAD) "Uploaded " else "Consolidated (not published): ",
  "opta_xmetrics.parquet: ",
  format(nrow(combined), big.mark = ","), " player-seasons, ",
  length(leagues), " leagues, ",
  "seasons ", paste(seasons, collapse = " to ")
))

cli_h1("Complete!")
