# 04_export_xmetrics.R
# Consolidate per-league/season xmetrics into a single parquet and upload
# to GitHub Releases (opta-latest tag) as opta_xmetrics.parquet.
#
# Run from panna directory: Rscript data-raw/epv/04_export_xmetrics.R
#
# Requires:
#   - pannadata/data/opta/xmetrics/{league}/{season}.parquet files
#     (generated by 03_calculate_player_xmetrics.R)
#
# Outputs:
#   - Uploads opta_xmetrics.parquet to peteowen1/pannadata opta-latest release

library(cli)
library(arrow)
devtools::load_all()

cli_h1("Export xMetrics to GitHub Releases")

# 1. Consolidate all xmetrics into one parquet ----

cli_h2("Step 1: Consolidate xmetrics")

xmetrics_root <- file.path(opta_data_dir(), "xmetrics")
if (!dir.exists(xmetrics_root)) {
  cli_abort(c(
    "No xmetrics directory found at {.path {xmetrics_root}}.",
    "i" = "Run 03_calculate_player_xmetrics.R first."
  ))
}

parquet_files <- list.files(xmetrics_root, pattern = "\\.parquet$",
                            recursive = TRUE, full.names = TRUE)
cli_alert_info("Found {length(parquet_files)} xmetrics parquet files")

if (length(parquet_files) == 0) {
  cli_abort("No parquet files found under {.path {xmetrics_root}}")
}

# Read and bind all files
all_data <- lapply(parquet_files, function(f) {
  tryCatch(arrow::read_parquet(f), error = function(e) {
    cli_warn("Failed to read {.path {f}}: {conditionMessage(e)}")
    NULL
  })
})
combined <- do.call(rbind, Filter(Negate(is.null), all_data))

cli_alert_success("Combined {format(nrow(combined), big.mark=',')} rows from {length(parquet_files)} files")

# Add competition column (Opta league name) for remote query compatibility
# query_remote_opta_parquet() filters on 'competition' using Opta league names
if ("league" %in% names(combined) && !"competition" %in% names(combined)) {
  combined$competition <- vapply(combined$league, function(lg) {
    tryCatch(to_opta_league(lg), error = function(e) lg)
  }, character(1))
  cli_alert_info("Added 'competition' column from league codes")
}

# 2. Write consolidated parquet ----

cli_h2("Step 2: Write consolidated parquet")

output_file <- file.path(tempdir(), "opta_xmetrics.parquet")
arrow::write_parquet(combined, output_file)
file_size <- file.size(output_file) / (1024 * 1024)
cli_alert_success("Written {.path opta_xmetrics.parquet} ({round(file_size, 1)} MB)")

# 3. Upload to GitHub Releases ----

cli_h2("Step 3: Upload to GitHub Releases")

repo <- "peteowen1/pannadata"
tag <- "opta-latest"

if (!requireNamespace("piggyback", quietly = TRUE)) {
  cli_abort("Package 'piggyback' is required. Install with: install.packages('piggyback')")
}

# Ensure release exists
tryCatch({
  piggyback::pb_list(repo = repo, tag = tag)
}, error = function(e) {
  cli_alert_info("Creating new release: {tag}")
  piggyback::pb_new_release(repo = repo, tag = tag)
  Sys.sleep(3)
})

cli_alert_info("Uploading to {repo} ({tag})...")
piggyback::pb_upload(
  file = output_file,
  repo = repo,
  tag = tag,
  name = "opta_xmetrics.parquet",
  overwrite = TRUE
)

cli_alert_success("Upload complete!")

# 4. Summary ----

cli_h2("Summary")

leagues <- if ("league" %in% names(combined)) unique(combined$league) else "unknown"
seasons <- if ("season" %in% names(combined)) range(combined$season) else "unknown"

cli_alert_success(paste0(
  "Uploaded opta_xmetrics.parquet: ",
  format(nrow(combined), big.mark = ","), " player-seasons, ",
  length(leagues), " leagues, ",
  "seasons ", paste(seasons, collapse = " to ")
))

cli_h1("Complete!")
