# 04b_export_xmetrics_bymatch.R
# Consolidate per-league/season xmetrics_bymatch into a single parquet and
# upload to GitHub Releases (opta-latest tag) as opta_xmetrics_bymatch.parquet.
#
# panna#126: enrich_match_stats_with_xmetrics(source = "remote") queries this
# file via query_remote_opta_parquet("xmetrics_bymatch", ...) — without it,
# GHA runners (which never have the local per-league/season tree, only
# whatever 01-02 downloaded) silently build xG-blind weekly PSR snapshots and
# game logs. Shares its consolidate/upload logic with 04_export_xmetrics.R via
# _xmetrics_export_common.R.
#
# Run from panna directory: Rscript data-raw/epv/04b_export_xmetrics_bymatch.R
#
# Requires:
#   - pannadata/data/opta/xmetrics_bymatch/{league}/{season}.parquet files
#     (generated by 03_calculate_player_xmetrics.R)
#
# Outputs:
#   - Uploads opta_xmetrics_bymatch.parquet to peteowen1/pannadata opta-latest release

library(cli)
library(arrow)
devtools::load_all()
source("data-raw/epv/_xmetrics_export_common.R")

cli_h1("Export per-match xMetrics to GitHub Releases")

cli_h2("Step 1: Consolidate xmetrics_bymatch")
combined <- export_consolidated_xmetrics("xmetrics_bymatch", "opta_xmetrics_bymatch.parquet",
                                          "player-matches")

cli_h2("Summary")

leagues <- if ("league" %in% names(combined)) unique(combined$league) else "unknown"
seasons <- if ("season" %in% names(combined)) range(combined$season) else "unknown"

cli_alert_success(paste0(
  "Uploaded opta_xmetrics_bymatch.parquet: ",
  format(nrow(combined), big.mark = ","), " player-matches, ",
  length(leagues), " leagues, ",
  "seasons ", paste(seasons, collapse = " to ")
))

cli_h1("Complete!")
