# Global variable declarations to avoid R CMD check NOTEs
# These are column names used in NSE (non-standard evaluation) operations

#' @importFrom stats setNames na.pass
NULL

# Suppress R CMD check notes for data.frame column names used in dplyr/tidyr
# Add column names as they are used in package functions

utils::globalVariables(c(
  # All column names are snake_case (via janitor::clean_names)

  # Match data columns
  "match_id",
  "match_url",
  "season",
  "season_end_year",
  "league",
  "date",
  "match_date",
  "home_team",
  "away_team",
  "home_goals",
  "away_goals",
  "home_score",
  "away_score",
  "home_xg",
  "away_xg",
  "home_x_g",
  "away_x_g",
  "fbref_id",
  "home_team_id",
  "away_team_id",

  # Player data columns
  "player",
  "player_id",
  "player_name",
  "player_href",
  "team",
  "home_away",
  "is_home",
  "pos",
  "position",
  "nation",
  "age",
  "min",
  "minutes",
  "is_starter",

  # Splint columns
  "splint_id",
  "splint_num",
  "start_minute",
  "end_minute",
  "duration",
  "npxgd",
  "npxgd_per_90",
  "npxg_home",
  "npxg_away",

  # Event columns
  "event_type",
  "minute",
  "is_goal",
  "is_sub",
  "is_penalty",
  "is_own_goal",

  # Statistics columns (snake_case versions)
  "gls",
  "ast",
  "sh",
  "so_t",
  "xg",
  "xg_expected",
  "npxg",
  "npxg_expected",
  "xag",
  "xag_expected",
  "pk",
  "pkatt",
  "crd_y",
  "crd_r",
  "touches",
  "tkl",
  "int",
  "blocks",
  "sca_sca",
  "gca_sca",
  "cmp_passes",
  "att_passes",
  "cmp_percent_passes",
  "prg_p_passes",
  "carries_carries",
  "prg_c_carries",
  "att_take_ons",
  "succ_take_ons",

  # Rate stat columns
  "per_100_seq",
  "team_sequences",
  "estimated_sequences",

  # RAPM/SPM/Panna columns
  "rapm",
  "o_rapm",
  "d_rapm",
  "spm",
  "o_spm",
  "d_spm",
  "panna",
  "o_panna",
  "d_panna",
  "spm_prior",
  "deviation",
  "coefficient",

  # Helper columns
  "n",
  "n_games",
  "total_minutes",
  "row_num",
  "value",
  "name",
  "label",
  ".",

  # Player timing columns
  "on_minute",
  "off_minute",

  # Player stats function columns
  "x1_3",
  "kp",
  "ppa",
  "crs_pa",
  "tkl_w",
  "clr",
  "err",
  "so_ta",
  "ga",
  "saves",
  "clean_sheet",

  # EPV model columns
  "chain_id",
  "chain_start_time",
  "chain_team_id",
  "chain_end_time",
  "chain_outcome",
  "chain_ends_in_goal",
  "chain_ends_in_shot",
  "chain_xg",
  "opponent_scores_next",
  "ends_in_goal",
  "next_opponent_chain_goal",
  "shots_in_chain",
  "action_in_chain",
  "action_type",
  "action_type_id",
  "action_id",
  "result",
  "bodypart",
  "start_x",
  "start_y",
  "end_x",
  "end_y",
  "time_seconds",
  "period_id",
  "type_id",
  "outcome",
  "opta_type_id",
  "opta_type_name",
  "original_event_id",
  "attacks_right",
  "qualifier_json",
  "qualifiers_parsed",

  # EPV feature columns
  "distance_to_goal",
  "angle_to_goal",
  "zone_id",
  "in_penalty_area",
  "in_final_third",
  "pass_distance",
  "pass_angle",
  "is_forward",
  "is_progressive",
  "xpass",
  "epv",
  "p_score",
  "p_concede",
  "p_score_delta",
  "p_concede_delta",
  "passer_credit",
  "receiver_credit",
  "scores_this_possession",
  "concedes_next_possession",

  # Additional columns
  "completed",
  "second",
  "big_chance",
  "situation",
  "body_part",
  "x",
  "y",

  # Duel opponent columns (from merge_duel_rows)
  "opponent_player_id",
  "opponent_player_name",

  # merge_duel_rows helper columns
  "is_duel",
  "next_match_id",
  "next_period_id",
  "next_time",
  "next_action_type",
  "next_team_id_duel",
  "next_result",
  "next_player_id",
  "next_player_name",
  "next_is_duel",
  "is_duel_pair",
  "is_winner",
  "is_loser",

  # normalize_spadl_coordinates helper columns
  "mean_x",
  "i.attacks_right",

  # calculate_physical_discontinuity columns
  "phys_end_x",
  "phys_end_y",
  "phys_next_x",
  "phys_next_y",
  "phys_disc",
  "ref_team",
  "next_team",
  "next_start_x",
  "next_start_y",

  # convert_opta_to_spadl helper columns
  "end_x_new",
  "end_y_new",

  # EPV delta calculation columns (lead-based: next action values)
  "next_epv",
  "next_team_id",

  # Pass credit assignment temp columns
  "passer_share",
  "passer_blame",
  "position_scale",

  # data.table special symbols
  "..available_cols",
  "..feature_cols",
  "..outcome_cols",
  "..result_cols",

  # Duel merge helper columns
  "x_sum",
  "is_same_type_duel",
  "is_cross_type_duel",

  # EPV credit assignment helper columns
  "is_period_boundary",
  "next_epv_fixed",
  "next_team_fixed",
  "next_action",

  # Possession chain helper columns
  "prev_team_id",

  # Additional EPV/RAPM columns from R CMD check
  "abs_coef",
  "action_time",
  "action_type_num",
  "added_time",
  "chain_break",
  "chain_duration",
  "dist_after",
  "dist_before",
  "dx",
  "dy",
  "epv_as_actor",
  "epv_as_receiver",
  "epv_delta",
  "epv_duel_blame",
  "epv_model",
  "epv_total",
  "opponent_credit",
  "event_id",
  "expected_xg",
  "feature",
  "goal_time",
  "has_shot",
  "is_headed_pass",
  "is_red_card",
  "last_action_result",
  "last_action_type",
  "mins_per_90",
  "minutes_played",
  "n_actions",
  "next_ends_in_goal",
  "next_goal_label",
  "next_goal_team",
  "next_shot_team",
  "next_shot_xg",
  "next_xg_label",
  "p_opponent_scores",
  "p_team_scores",
  "player_credit",
  "possession_change",
  "possession_velocity",
  "prev_action_type",
  "prev_period_id",
  "prev_result",
  "prev_time",
  "receiver_player_id",
  "receiver_player_name",
  "receiver_team_id",
  "result_success",
  "seconds_since_chain_start",
  "shot_time",
  "shot_xg",
  "team_id",
  "time_first",
  "time_last",
  "x_first",
  "x_last",
  "x_progression",

  # data.table join prefix columns (i. prefix)
  "i.action_id",
  "i.end_minute",
  "i.match_id",
  "i.period_id",
  "i.splint_num",
  "i.start_minute",
  "i.team_id",

  # data.table join prefix columns (x. prefix)
  "x.goal_team",
  "x.is_home",
  "x.player_id",
  "x.player_name",
  "x.shot_team",
  "x.shot_xg",
  "x.team",

  # xmetrics (derive_xa / aggregate_player_xmetrics) columns
  "xa",
  "goals",
  "is_key_pass",
  "is_assist",
  "prev_action_id",
  "prev_player_id",
  "prev_player_name",
  "shots_on_target",
  "penalty_goals",
  "npgoals",
  "goals_minus_xg",
  "xg_per90",
  "xa_per90",
  "xpass_overperformance",
  "xpass_overperformance_per90",
  "xpass_avg",
  "sum_xpass",
  "passes_attempted",
  "passes_completed",

  # Opta pipeline columns (player-ratings-opta)
  "team_name",
  "team_position",
  "sub_on_minute",
  "sub_off_minute",
  "appearances",
  "primary_team",
  "npxg_per90",
  "xa_per90_xmetrics",
  "xpass_overperformance_per90_xmetrics",

  # Opta SPM expanded feature columns
  "fwd_zone_pass_p90",
  "open_play_pass_p90",
  "error_lead_to_shot_p90",
  "error_lead_to_goal_p90",
  "att_fastbreak_p90",
  "shot_fastbreak_p90",
  "att_openplay_p90",
  "att_setpiece_p90",
  "att_headed_p90",
  "att_one_on_one_p90",
  "crosses_open_play_p90",
  "penalty_won_p90",
  "penalty_conceded_p90",
  "offtarget_att_assist_p90",
  "last_man_tackle_p90",
  "six_yard_block_p90",
  "clearance_off_line_p90",
  "keeper_sweeper_p90",
  "attempts_conceded_ibox_p90",
  "attempts_conceded_obox_p90",
  "gk_smother_p90",
  "unsuccessful_touch_p90",
  "overrun_p90",
  "flick_on_p90",
  "fwd_zone_pass_accuracy",
  "open_play_pass_accuracy",
  "crosses_open_play_accuracy",
  "bad_touch_rate",
  "errors_total_p90",
  "headed_goal_rate",
  "flick_on_accuracy",
  "keeper_sweeper_accuracy",

  # Opta SPM Round 2 feature columns
  "back_zone_pass_p90",
  "chipped_pass_p90",
  "att_rf_total_p90",
  "att_lf_total_p90",
  "att_ibox_goal_p90",
  "att_obox_goal_p90",
  "att_ibox_target_p90",
  "att_obox_target_p90",
  "hit_woodwork_p90",
  "att_pen_goal_p90",
  "att_pen_miss_p90",
  "pen_goals_conceded_p90",
  "keeper_pickup_p90",
  "poss_lost_ctrl_p90",
  "long_pass_own_to_opp_p90",
  "fifty_fifty_p90",
  "fifty_fifty_won_p90",
  "back_zone_pass_accuracy",
  "chipped_pass_accuracy",
  "ibox_goal_rate",
  "obox_goal_rate",
  "penalty_conversion",
  "long_pass_own_to_opp_accuracy",
  "fifty_fifty_success",
  "poss_lost_ctrl_per_touch"
))
