# Global variable declarations to avoid R CMD check NOTEs
# These are column names used in NSE (non-standard evaluation) operations

#' @importFrom magrittr %>%
#' @export
magrittr::`%>%`

#' @importFrom stats setNames na.pass
NULL

# Suppress R CMD check notes for data.frame column names used in dplyr/tidyr
# Add column names as they are used in package functions

utils::globalVariables(c(
  # All column names are snake_case (via janitor::clean_names)

  # Match data columns
  "match_id",
  "match_url",
  "season",
  "season_end_year",
  "league",
  "date",
  "match_date",
  "home_team",
  "away_team",
  "home_goals",
  "away_goals",
  "home_score",
  "away_score",
  "home_xg",
  "away_xg",
  "home_x_g",
  "away_x_g",
  "fbref_id",
  "home_team_id",
  "away_team_id",

  # Player data columns
  "player",
  "player_id",
  "player_name",
  "player_href",
  "team",
  "home_away",
  "is_home",
  "pos",
  "position",
  "nation",
  "age",
  "min",
  "minutes",
  "is_starter",

  # Splint columns
  "splint_id",
  "splint_num",
  "start_minute",
  "end_minute",
  "duration",
  "npxgd",
  "npxgd_per_90",
  "npxg_home",
  "npxg_away",

  # Event columns
  "event_type",
  "minute",
  "is_goal",
  "is_sub",
  "is_penalty",
  "is_own_goal",

  # Statistics columns (snake_case versions)
  "gls",
  "ast",
  "sh",
  "so_t",
  "xg",
  "xg_expected",
  "npxg",
  "npxg_expected",
  "xag",
  "xag_expected",
  "pk",
  "pkatt",
  "crd_y",
  "crd_r",
  "touches",
  "tkl",
  "int",
  "blocks",
  "sca_sca",
  "gca_sca",
  "cmp_passes",
  "att_passes",
  "cmp_percent_passes",
  "prg_p_passes",
  "carries_carries",
  "prg_c_carries",
  "att_take_ons",
  "succ_take_ons",

  # Rate stat columns
  "per_100_seq",
  "team_sequences",
  "estimated_sequences",

  # RAPM/SPM/Panna columns
  "rapm",
  "o_rapm",
  "d_rapm",
  "spm",
  "o_spm",
  "d_spm",
  "panna",
  "o_panna",
  "d_panna",
  "spm_prior",
  "deviation",
  "coefficient",

  # Helper columns
  "n",
  "n_games",
  "total_minutes",
  "row_num",
  "value",
  "name",
  "label",
  ".",

  # Player timing columns
  "on_minute",
  "off_minute",

  # Player stats function columns
  "x1_3",
  "kp",
  "ppa",
  "crs_pa",
  "tkl_w",
  "clr",
  "err",
  "so_ta",
  "ga",
  "saves",
  "clean_sheet",

  # EPV model columns
  "chain_id",
  "chain_start_time",
  "chain_team_id",
  "chain_end_time",
  "chain_outcome",
  "chain_ends_in_goal",
  "chain_ends_in_shot",
  "chain_xg",
  "opponent_scores_next",
  "ends_in_goal",
  "next_opponent_chain_goal",
  "shots_in_chain",
  "action_in_chain",
  "action_type",
  "action_type_id",
  "action_id",
  "result",
  "bodypart",
  "start_x",
  "start_y",
  "end_x",
  "end_y",
  "time_seconds",
  "period_id",
  "type_id",
  "outcome",
  "opta_type_id",
  "original_event_id",
  "attacks_right",
  "qualifier_json",
  "qualifiers_parsed",

  # EPV feature columns
  "distance_to_goal",
  "angle_to_goal",
  "zone_id",
  "in_penalty_area",
  "in_final_third",
  "pass_distance",
  "pass_angle",
  "is_forward",
  "is_progressive",
  "xpass",
  "xg",
  "epv",
  "p_score",
  "p_concede",
  "p_score_delta",
  "p_concede_delta",
  "passer_credit",
  "receiver_credit",
  "scores_this_possession",
  "concedes_next_possession",

  # Additional columns
  "completed",
  "second",
  "big_chance",
  "situation",
  "body_part",
  "x",
  "y",

  # Duel opponent columns (from merge_duel_rows)
  "opponent_player_id",
  "opponent_player_name",

  # EPV delta calculation columns
  "prev_epv",
  "prev_team_id",

  # Own goal indicator (Opta qualifier 28)
  "is_own_goal",

  # Pass credit assignment temp columns
  "passer_share",
  "passer_blame",

  # data.table special symbols
  "..feature_cols",
  "..outcome_cols",
  "..result_cols",

  # Additional EPV/RAPM columns from R CMD check
  "abs_coef",
  "action_time",
  "action_type_num",
  "added_time",
  "chain_break",
  "chain_duration",
  "dist_after",
  "dist_before",
  "dx",
  "dy",
  "epv_as_actor",
  "epv_as_receiver",
  "epv_delta",
  "epv_total",
  "event_id",
  "expected_xg",
  "feature",
  "goal_time",
  "has_shot",
  "is_headed_pass",
  "is_red_card",
  "last_action_result",
  "last_action_type",
  "mins_per_90",
  "minutes_played",
  "n_actions",
  "next_ends_in_goal",
  "next_goal_label",
  "next_goal_team",
  "next_shot_team",
  "next_shot_xg",
  "next_team_id",
  "next_xg_label",
  "p_opponent_scores",
  "p_team_scores",
  "player_credit",
  "possession_change",
  "possession_velocity",
  "prev_action_type",
  "prev_period_id",
  "prev_result",
  "prev_time",
  "receiver_player_id",
  "receiver_player_name",
  "receiver_team_id",
  "result_success",
  "seconds_since_chain_start",
  "shot_time",
  "shot_xg",
  "team_id",
  "time_first",
  "time_last",
  "x_first",
  "x_last",
  "x_progression",

  # data.table join prefix columns (i. prefix)
  "i.action_id",
  "i.end_minute",
  "i.match_id",
  "i.period_id",
  "i.splint_num",
  "i.start_minute",
  "i.team_id",

  # data.table join prefix columns (x. prefix)
  "x.goal_team",
  "x.is_home",
  "x.player_id",
  "x.player_name",
  "x.shot_team",
  "x.shot_xg",
  "x.team"
))
